name: Build and Test Sample

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
      path:
        required: true
        type: string
      module:
        default: "app"
        type: string
    secrets:
      compose_store_password:
        description: 'password for the keystore'
        required: true
      compose_key_alias:
        description: 'alias for the keystore'
        required: true
      compose_key_password:
        description: 'password for the key'
        required: true
concurrency:
  group: ${{ inputs.name }}-build-${{ github.ref }}
  cancel-in-progress: true
env:
  compose_store_password: ${{ secrets.compose_store_password }}
  compose_key_alias: ${{ secrets.compose_key_alias }}
  compose_key_password: ${{ secrets.compose_key_password }}
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Copy CI gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu'

      - name: Generate cache key
        run: ./scripts/checksum.sh ${{ inputs.path }} checksum.txt

      - uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches/modules-*
            ~/.gradle/caches/jars-*
            ~/.gradle/caches/build-cache-*
          key: gradle-${{ hashFiles('checksum.txt') }}
            
      - name: Run Screenshot Tests
        working-directory: ${{ inputs.path }}
        run: ./gradlew validateDebugScreenshotTest --stacktrace

      - name: Upload build reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-reports
          path: ${{ inputs.path }}/${{ inputs.module }}/build/reports
